### ISSUE TITLE
com.hortonworks.das not found on maven

### ISSUE THREAD

**Issue by yixin19** [hortonworks/data_analytics_studio#2]
[ERROR] Failed to execute goal on project das-commons: Could not resolve dependencies for project com.hortonworks.das:das-commons:jar:1.2.0-SNAPSHOT: Could not find artifact org.apache.hadoop:hadoop-common:jar:3.1.0.3.0.0.0-1634 in central (https://repo.maven.apach
e.org/maven2) -> [Help 1]

**Comment by kholis** [comment]
me too

```
[ERROR] Failed to execute goal on project das-commons: Could not resolve dependencies for project com.hortonworks.das:das-commons:jar:1.2.0-SNAPSHOT: Could not find artifact org.apache.hadoop:hadoop-common:jar:3.1.0.3.0.0.0-1634 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```
